### ISSUE TITLE
About compressed source code

### ISSUE THREAD

**Issue by catroll** [FredGandt/RFCRestyle#1]
I love this extension, but it's source code seems to be compressed.
So, its difficult to edit.

**Comment by catroll** [comment]
Can you keep codes under `RFCRestyle` uncompressed version?

**Comment by FredGandt** [comment]
Hi catroll.
I don't have the code for this extension in a fully unminified state at this time; in order to provide it, I will first need to create it by extrapolation. Since that process will provide no practical benefit (as far as functionality is concerned) and will be quite laborious, I don't feel any enthusiasm for doing it.
I will, however, make an effort to get around to it in the next few weeks.

**Comment by FredGandt** [comment]
Hi again @catroll .
I have created the fully unminified (maxified™) code as requested and added it as the subdirectory "Deminified".
I have renamed the "RFCRestyle" subdirectory to "Expanded".
I hope this helps you out and thanks for your interest :)

**Comment by catroll** [comment]
Thank you very much.
I need browser RFC frequently for job demand (my work is email development).
This extension is very useful for me.
