### ISSUE TITLE
Alt-T (Option-T) doesn't work in Chrome on macOS?

### ISSUE THREAD

**Issue by tddschn** [FredGandt/RFCRestyle#2]
I was reading https://datatracker.ietf.org/doc/html/rfc8962 and it seemed that option-T didn't work (nothing happens when I pressed the shortcut).  
Option-L didn't work either.

A great extension overall :) Thank you for making this for free!

Chrome version: 91
OS: macOS 11.4

**Comment by FredGandt** [comment]
<kbd>Alt</kbd>+<kbd>T</kbd> and <kbd>Alt</kbd>+<kbd>L</kbd> function as expected on that and other RFCs; I'm afraid I don't have a Mac to test on myself, and can only expect Chrome to respond correctly to keyboard instructions on Mac OS.
As I understand it, you're correct to expect <kbd>Option</kbd>+<kbd>T</kbd> and <kbd>Option</kbd>+<kbd>L</kbd> to act as the <kbd>Alt</kbd>ernatives do.

**Note:** the Legend will only be visible at the very top of the page when it's open.
* If you have "Keep Table of Contents open" checked, the respective keyboard shortcut will only focus the ToC, since it will already be open, otherwise the ToC will open and gain focus.
* If the Legend is already open, the respective keyboard shortcut will do nothing at all, since the Legend is not focusable.
* Neither shortcut will close the respective "popup" (for want of a better word).
* The ToC will remain open no matter what else happens if "Keep Table of Contents open" is checked, but otherwise will close when any part of the page is clicked.
* The Legend will close when any part of the page is clicked.

**Please confirm that you're not seeing this behaviour.**

P.S. Thanks for posting your issue here instead of the Web Store; it's a far more useful interface :)

**Comment by tddschn** [comment]
Thanks for the quick reply!

No, I don't have 'Keep ToC open' checked.
<img src=https://user-images.githubusercontent.com/45612704/122133402-32913180-ce6f-11eb-867b-56635bf6df1e.png width=300>

I tried Option+L with Legend closed, and it didn't open.

_However, `accesskey` + L/T does work!_ (found it from [`init.js`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/FredGandt/RFCRestyle%24%40master+accesskey&patternType=literal)
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey  
These keyboard shortcuts for me:
<img src=https://user-images.githubusercontent.com/45612704/122134731-c82dc080-ce71-11eb-81e3-87b563f551c0.png width=500>

**Comment by FredGandt** [comment]
Ah, so it's actually just poor documentation on my part ... ***feels deep shame***.

Yeah, I was surprised that it wasn't working since the HTML `accesskey` attribute is as old as dirt and an essential part of accessibility (exactly why I used it instead of a custom JavaScript solution). It's this kind of sh*t that makes web development tiring ;)

I'll amend the documentation to be less Windoze-centric :)
Thanks for your effort in bringing this to my attention, and sorry for the confusion.
